In [ ]:
!pip install selenium webdriver-manager

In [4]:
import undetected_chromedriver as uc
import time
import os

def check_lazada_html(url, save_file="lazada_html.html"):
    # Fix cứng mặc định dùng Profile 1
    profile_id = 1
    
    print(f"[Luồng {profile_id}] 🔄 Đang khởi tạo trình duyệt Chrome...")
    options = uc.ChromeOptions()
    options.add_argument('--disable-gpu')
    options.add_argument('--window-size=1920,1080')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    
    # CHIẾN THUẬT QUAN TRỌNG: MỖI LUỒNG DÙNG 1 FOLDER PROFILE KHÁC NHAU
    profile_path = rf'C:\Users\ADMIN\ChromeProfileData_{profile_id}'
    options.add_argument(f'--user-data-dir={profile_path}')

    try:
        driver = uc.Chrome(options=options)
        
        print(f"Đang truy cập: {url}")
        driver.get(url)
        
        print("Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...")
        time.sleep(10) # Tăng thời gian chờ lên một xíu để bạn có thời gian kéo captcha nếu bị hỏi
        
        # Cuộn trang từ từ để nạp hết các sản phẩm và ảnh
        for i in range(5):
            driver.execute_script(f"window.scrollTo(0, {(i+1)*800});")
            time.sleep(1)
        
        html_source = driver.page_source
        
        # LƯU FILE HTML
        with open(save_file, "w", encoding="utf-8") as f:
            f.write(html_source)
            
        print("-" * 50)
        print(f"✅ THÀNH CÔNG: Đã lưu mã HTML vào file {os.path.abspath(save_file)}!")
        print(f"Độ dài mã HTML: {len(html_source)} ký tự.")
        print("-" * 50)
        
        return html_source

    except Exception as e:
        print(f"❌ Xảy ra lỗi: {e}")
        return None
        
    finally:
        if 'driver' in locals():
            driver.quit()
        print("Đã đóng trình duyệt.")

In [5]:
from bs4 import BeautifulSoup
import pandas as pd
import re

def extract_lazada_data(html_file_path, category):
    print(f"Đang đọc file HTML: {html_file_path}")
    
    # Mở và đọc file HTML (nhớ dùng utf-8 nếu không sẽ bị lỗi font tiếng Việt)
    with open(html_file_path, "r", encoding="utf-8") as file:
        html_content = file.read()
        
    # Tạo đối tượng BeautifulSoup để parse HTML
    soup = BeautifulSoup(html_content, "html.parser")
    
    # Tìm TẤT CẢ các thẻ div chứa thông tin của một sản phẩm
    # Lazada dùng thuộc tính data-qa-locator="product-item" để đánh dấu
    product_items = soup.find_all(attrs={"data-qa-locator": "product-item"})
    print(f"✅ Tìm thấy {len(product_items)} sản phẩm trong trang!")
    
    parsed_data = []
    
    for item in product_items:
        # 1. Tên, Link và ID
        a_tag = item.find("a", title=True)
        title = a_tag["title"] if a_tag else None
        
        link = a_tag["href"] if a_tag and "href" in a_tag.attrs else None
        product_id = None
        
        if link:
            if link.startswith("//"):
                link = "https:" + link
            # Dùng Regex để bắt một dãy số đứng sau chữ 'pdp-i' trong link
            id_match = re.search(r'pdp-i(\d+)\.html', link)
            if id_match:
                product_id = id_match.group(1)

            
        # 2. Giá sản phẩm
        price_tag = item.find("span", class_="ooOxS")
        price = price_tag.text.strip() if price_tag else None
        
        # 3. Giảm giá (VD: 50% Off)
        discount_tag = item.find("span", class_="IcOsH")
        discount = discount_tag.text.strip() if discount_tag else None
        
        # 4. Đã bán
        sold_tag = item.find("span", class_="_1cEkb")
        sold = sold_tag.text.strip() if sold_tag else None
        
        # 5. Số lượt đánh giá
        rating_tag = item.find("span", class_="qzqFw")
        rating_count = rating_tag.text.strip().replace("(", "").replace(")", "") if rating_tag else None
        
        
        rating_score = None

        # 6. Địa điểm bán (Hà Nội, Nước ngoài...)
        location_tag = item.find("span", class_="oa6ri")
        location = location_tag.text.strip() if location_tag else None
        
        # 7. Hình ảnh
        img_tag = item.find("img")
        image_url = img_tag["src"] if img_tag and "src" in img_tag.attrs else None

        # 8. Tên shop
        shop_name = None
        
        # 8. Shop URL
        shop_url = None
        
        parsed_data.append({
            "ID Sản phẩm": product_id,
            "Tên sản phẩm": title,
            "Danh mục": category,
            "Giá": price,
            "Giảm giá": discount,
            "Đã bán": sold,
            "Điểm đánh giá": rating_score, 
            "Lượt đánh giá": rating_count,
            "Địa điểm": location,
            "Đường dẫn": link,
            "Hình ảnh": image_url,
            "Tên shop": shop_name,
            "Shop URL": shop_url
        })
        
    return parsed_data

In [6]:
# ===================== CHẠY THỬ / CRAWL NHIỀU TRANG =====================
import os
import pandas as pd # Đảm bảo đã import pandas

BASE_URL = "https://www.lazada.vn/catalog/?from=hp_categories&page={page}&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel"
TOTAL_PAGES = 130

# --- THÊM PHẦN TẠO THƯ MỤC ---
HTML_DIR = "lazada_tpnam_html_pages" # Tên thư mục bạn muốn lưu file HTML
if not os.path.exists(HTML_DIR):
    os.makedirs(HTML_DIR)
# -----------------------------

all_data = []

for page in range(1, TOTAL_PAGES + 1):
    url = BASE_URL.format(page=page)
    
    # --- CẬP NHẬT ĐƯỜNG DẪN LƯU FILE VÀO THƯ MỤC ---
    html_file = os.path.join(HTML_DIR, f"lazada_page_{page}.html")
    # ----------------------------------------------
    
    print(f"\n[{page}/{TOTAL_PAGES}] Đang crawl trang {page}...")
    html_data = check_lazada_html(url, html_file)
    
    if html_data:
        if "product-item" in html_data or "Bm3ON" in html_data:
            print("🟢 CÓ dữ liệu sản phẩm!")
        else:
            print("🔴 KHÔNG tìm thấy sản phẩm — có thể bị chặn hoặc hết trang.")
        
        data = extract_lazada_data(html_file, "Trang phục nam")
        all_data.extend(data)
        print(f"→ Trang này: {len(data)} sản phẩm | Tổng cộng: {len(all_data)}")
    else:
        print(f"Không lấy được HTML trang {page}, bỏ qua.")

# Tổng hợp và hiển thị
print("\n" + "=" * 50)
print("BƯỚC 3: TỔNG HỢP")
print("=" * 50)

df_raw = pd.DataFrame(all_data)
print(f"Tổng trước dedup : {len(df_raw)}")
print(f"ID bị null       : {df_raw['ID Sản phẩm'].isna().sum()}")

dupes = df_raw[df_raw.duplicated(subset=["ID Sản phẩm"], keep=False)]
print(f"Số dòng trùng ID : {len(dupes)}")

df = df_raw.drop_duplicates(subset=["ID Sản phẩm"], keep="first").reset_index(drop=True)
print(f"\nHOÀN THÀNH! Tổng sản phẩm duy nhất: {len(df)}")

display(df.head())

DATA_DIR = "data"
if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)

# Nối đường dẫn lưu file
csv_path = os.path.join(DATA_DIR, "lazada_trang_phuc_nam.csv")
# -------------------------------------

# Lưu file
df.to_csv(csv_path, index=False, encoding="utf-8-sig")
print(f"Đã lưu thành công file CSV tại: {csv_path}!")

[1/130] Đang crawl trang 1...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=1&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_1.html!
Độ dài mã HTML: 4833518 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_1.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 40

[2/130] Đang crawl trang 2...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=2&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_2.html!
Độ dài mã HTML: 4449750 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_2.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 80

[3/130] Đang crawl trang 3...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=3&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_3.html!
Độ dài mã HTML: 5923756 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_3.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 120

[4/130] Đang crawl trang 4...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=4&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_4.html!
Độ dài mã HTML: 5059512 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_4.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 160

[5/130] Đang crawl trang 5...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=5&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_5.html!
Độ dài mã HTML: 6698002 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_5.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 200

[6/130] Đang crawl trang 6...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=6&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_6.html!
Độ dài mã HTML: 5029163 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_6.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 240

[7/130] Đang crawl trang 7...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=7&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_7.html!
Độ dài mã HTML: 4110680 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_7.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 280

[8/130] Đang crawl trang 8...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=8&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_8.html!
Độ dài mã HTML: 6466453 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_8.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 320

[9/130] Đang crawl trang 9...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=9&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_9.html!
Độ dài mã HTML: 7691396 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_9.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 360

[10/130] Đang crawl trang 10...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=10&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_10.html!
Độ dài mã HTML: 5000230 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_10.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 400

[11/130] Đang crawl trang 11...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=11&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_11.html!
Độ dài mã HTML: 6063538 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_11.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 440

[12/130] Đang crawl trang 12...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=12&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_12.html!
Độ dài mã HTML: 7864672 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_12.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 480

[13/130] Đang crawl trang 13...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=13&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_13.html!
Độ dài mã HTML: 5380114 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_13.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 520

[14/130] Đang crawl trang 14...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=14&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_14.html!
Độ dài mã HTML: 6564539 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_14.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 560

[15/130] Đang crawl trang 15...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=15&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_15.html!
Độ dài mã HTML: 5487190 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_15.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 600

[16/130] Đang crawl trang 16...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=16&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_16.html!
Độ dài mã HTML: 7922857 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_16.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 640

[17/130] Đang crawl trang 17...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=17&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_17.html!
Độ dài mã HTML: 5373434 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_17.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 680

[18/130] Đang crawl trang 18...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=18&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_18.html!
Độ dài mã HTML: 6693818 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_18.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 720

[19/130] Đang crawl trang 19...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=19&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_19.html!
Độ dài mã HTML: 7424556 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_19.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 760

[20/130] Đang crawl trang 20...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=20&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_20.html!
Độ dài mã HTML: 6621359 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_20.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 800

[21/130] Đang crawl trang 21...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=21&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_21.html!
Độ dài mã HTML: 2658172 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_21.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 840

[22/130] Đang crawl trang 22...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=22&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_22.html!
Độ dài mã HTML: 4446751 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_22.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 880

[23/130] Đang crawl trang 23...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=23&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_23.html!
Độ dài mã HTML: 6958635 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_23.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 920

[24/130] Đang crawl trang 24...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=24&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_24.html!
Độ dài mã HTML: 4811478 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_24.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 960

[25/130] Đang crawl trang 25...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
Đang truy cập: https://www.lazada.vn/catalog/?from=hp_categories&page=25&q=Trang%20ph%E1%BB%A5c%20nam&service=all_channel&spm=a2o4n.pdp_revamp.cate_9.1.4797739f2Vrqn8&src=all_channel
Đang đợi trang load 10 giây (bạn hãy giải captcha nếu có)...
--------------------------------------------------
✅ THÀNH CÔNG: Đã lưu mã HTML vào file c:\Users\ADMIN\Documents\Chuyen Nganh\HK2\Trực quan hóa dữ liệu\Lab 1\lazada_tpnam_html_pages\lazada_page_25.html!
Độ dài mã HTML: 4703861 ký tự.
--------------------------------------------------
Đã đóng trình duyệt.
🟢 CÓ dữ liệu sản phẩm!
Đang đọc file HTML: lazada_tpnam_html_pages\lazada_page_25.html
✅ Tìm thấy 40 sản phẩm trong trang!
→ Trang này: 40 sản phẩm | Tổng cộng: 1000

[26/130] Đang crawl trang 26...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...

,ID Sản phẩm,Tên sản phẩm,Danh mục,Giá,Giảm giá,Đã bán,Điểm đánh giá,Lượt đánh giá,Địa điểm,Đường dẫn,Hình ảnh,Tên shop,Shop URL
0,2562394269,Jeep Spirit Outdoor Windbreaker Clothing Men's...,Trang phục nam,269.999 ₫,51% Off,1.9K Đã bán,None,753,Thành phố Hồ Chí Minh,https://www.lazada.vn/products/pdp-i2562394269...,https://img.lazcdn.com/g/p/6199d4f39b850a5a986...,None,None
1,1329853406,"Bộ Đồ Thể Thao Xtep, Bộ Đồ Chạy Bộ Hai Mảnh Nh...",Trang phục nam,495.280 ₫,47% Off,550 Đã bán,None,207,China,https://www.lazada.vn/products/pdp-i1329853406...,https://img.lazcdn.com/g/p/a3467728107f63b3090...,None,None
2,3064932258,MOLAN Áo phông nam nam ngắn tay thể thao cổ tr...,Trang phục nam,38.000 ₫,50% Off,331 Đã bán,None,80,China,https://www.lazada.vn/products/pdp-i3064932258...,https://img.lazcdn.com/g/p/becc8492da7c50d2daa...,None,None
3,2250151368,"Trang Phục Tay Ngắn Thời Đường, Bộ Đồ Nam Chất...",Trang phục nam,212.430 ₫,33% Off,822 Đã bán,None,268,Ninh Bình,https://www.lazada.vn/products/pdp-i2250151368...,https://img.lazcdn.com/g/p/a71cbab85bdc3c27dc1...,None,None
4,2964031932,Bộ Đồ Lụa Băng Tay Dài Cho Nam Mùa Xuân Hè Tập...,Trang phục nam,190.800 ₫,10% Off,288 Đã bán,None,28,China,https://www.lazada.vn/products/pdp-i2964031932...,https://img.lazcdn.com/g/ff/kf/Sd156b66e555c42...,None,None

OSError: [Errno 28] No space left on device

In [7]:
DATA_DIR = "data"
if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)

# Nối đường dẫn lưu file
csv_path = os.path.join(DATA_DIR, "lazada_trang_phuc_nam.csv")
# -------------------------------------

# Lưu file
df.to_csv(csv_path, index=False, encoding="utf-8-sig")
print(f"Đã lưu thành công file CSV tại: {csv_path}!")

Đã lưu thành công file CSV tại: data\lazada_trang_phuc_nam.csv!

In [2]:
import pandas as pd

df = pd.read_csv("data/lazada_trang_phuc_nam.csv")

In [3]:
import time
import re 
from bs4 import BeautifulSoup
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from concurrent.futures import ThreadPoolExecutor
import threading
import queue
import pandas as pd
import random
import winsound  # 🔊 Thêm thư viện phát âm thanh trên Windows
import os

MAX_WORKERS = 6  # Số Chrome chạy song song

# ===================== SỬA LỖI ĐA LUỒNG =====================
# 1. Hàng đợi để phân phát ID Profile cho các luồng (Để chia làm 3 thư mục profile khác nhau)
profile_queue = queue.Queue()
for i in range(MAX_WORKERS):
    profile_queue.put(i)  # Thêm ID: 0, 1, 2 vào hàng đợi

# 2. Khóa (Lock) để tránh các luồng đụng độ nhau khi tạo file chromedriver
chrome_init_lock = threading.Lock()

def crawl_lazada_product(url):
    # Lấy 1 ID từ hàng đợi rảnh rỗi (Ngăn không cho luồng khác xài)
    profile_id = profile_queue.get()
    extracted_data = {}
    driver = None
    
    try:
        print(f"[Luồng {profile_id}] 🔄 Đang khởi tạo trình duyệt Chrome...")
        options = uc.ChromeOptions()
        options.add_argument('--disable-gpu')
        options.add_argument('--window-size=1920,1080')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        
        # CHIẾN THUẬT QUAN TRỌNG: MỖI LUỒNG DÙNG 1 FOLDER PROFILE KHÁC NHAU
        profile_path = rf'C:\Users\ADMIN\ChromeProfileData_{profile_id}'
        options.add_argument(f'--user-data-dir={profile_path}')
        
        #DÙNG KHÓA KHI KHỞI TẠO ĐỂ TRÁNH LỖI WINERROR 183
        with chrome_init_lock:
            driver = uc.Chrome(options=options)
            
        print(f"[Luồng {profile_id}] đang truy cập URL: {url}")
        driver.get(url)
        
        # --- CƠ CHẾ KIỂM TRA & VƯỢT BOT DETECTION ---
        time.sleep(3)
        if "we need to check if you are a robot" in driver.page_source.lower() or "recaptcha" in driver.page_source.lower() or "bảo vệ bởi ddos" in driver.page_source.lower():
            print(f"[Luồng {profile_id}] ⚠️ PHÁT HIỆN BOT! Vui lòng tự giải Captcha trên cửa sổ {profile_id}...")
            
            # ========================================================
            # Phát âm thanh cảnh báo bíp bíp liên tục (5 tiếng)
            try:
                for _ in range(5):
                    # winound.Beep(tần số_Hz, thời_gian_kêu_ms)
                    winsound.Beep(1500, 500) 
                    time.sleep(0.1)
            except:
                pass
            # ========================================================

            try:
                WebDriverWait(driver, 60).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'pdp-mod-review'))
                )
                print(f"[Luồng {profile_id}] ✅ Đã qua bước xác minh.")
            except Exception:
                print(f"[Luồng {profile_id}] ❌ Quá 60s không giải được.")
        
        # Chờ load trang
        try:
            WebDriverWait(driver, 15).until(EC.presence_of_element_located((By.CLASS_NAME, 'pdp-mod-review')))
            driver.execute_script("window.scrollBy(0, 800);")
            time.sleep(4)
            driver.execute_script("window.scrollBy(0, 1000);")
            time.sleep(2)
        except Exception:
            pass
        
        # Trích xuất HTML
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')
        
        # 1. TÊN SHOP VÀ LINK SHOP
        seller_element = soup.select_one('.seller-name-v2__detail-name, .seller-name-v2__top a, .seller-name__detail')
        if seller_element:
            extracted_data['Shop Name'] = seller_element.get_text(strip=True)
            link = seller_element.get('href')
            if not link and seller_element.find_parent('a'):
                link = seller_element.find_parent('a').get('href')
            extracted_data['Shop URL'] = "https:" + link if link and link.startswith('//') else (link or "")
        else:
            extracted_data['Shop Name'] = ""
            extracted_data['Shop URL'] = ""
            
        # 2. ĐÁNH GIÁ TRUNG BÌNH
        score_tag = soup.select_one('.container-star-v2-score, .score-average, .score, .rating-score, .pdp-review-summary__stars')
        if score_tag:
            extracted_data['Rating Score'] = score_tag.get_text(strip=True)
        else:
            all_text = ' '.join(soup.stripped_strings)
            score_regex = re.search(r'(\d\.\d)\s*\(\d+\)', all_text)
            extracted_data['Rating Score'] = score_regex.group(1) if score_regex else "" # Để trống
            
    except Exception as e:
        print(f"[Luồng {profile_id}] ❌ Lỗi khi thao tác với Chrome: {e}")
    finally:
        # Quan trọng 1: Phải luôn tắt driver kể cả khi có lỗi
        try:
            if driver:
                driver.quit()
        except:
            pass
        # Quan trọng 2: Hoàn trả lại quyền dùng profile_id vào hàng đợi cho luồng sau dùng tiếp
        profile_queue.put(profile_id)
        
    return extracted_data


# ===================== QUẢN LÝ CHẠY ĐA LUỒNG =====================
# (Giả định bạn đã có biến df chứa số liệu ở các Cell trên)
df_missing = df[df['Điểm đánh giá'].isna() | df['Shop URL'].isna()].copy()
print(f"→ Sẽ crawl {len(df_missing)} sản phẩm với {MAX_WORKERS} luồng song song...")

def crawl_one(args):
    idx, row = args
    url = row["Đường dẫn"]
    
    if pd.isna(url):
        return idx, None
    
    # Random delay này vẫn giữ để giảm tải khi mới vào, kết hợp với "Lock" ở trên là an toàn tuyệt đối 100%
    time.sleep(random.uniform(1, 4)) 
    
    detail = crawl_lazada_product(url)
    if detail:
        print(f"✅ [{idx}] {row['Tên sản phẩm'][:30]} | Rating: {detail.get('Rating Score') or 'Rỗng'} | Shop: {detail.get('Shop Name') or 'Rỗng'}")
    return idx, detail

# Chạy đa luồng
with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = executor.map(crawl_one, df_missing.iterrows())
    
    for idx, detail in futures:
        if detail is None or not detail:
            continue
        # Dùng 'in detail' để lưu cả những thành phần "" vào file excel cuối
        if "Rating Score" in detail:
            df.at[idx, "Điểm đánh giá"] = detail["Rating Score"]
        if "Shop Name" in detail:
            df.at[idx, "Tên shop"] = detail["Shop Name"]
        if "Shop URL" in detail:
            df.at[idx, "Shop URL"] = detail["Shop URL"]

# Đường dẫn lưu file
csv_path = os.path.join("data", "lazada_trang_phuc_nam.csv")
# Lưu file (Đảm bảo tên file bạn muốn)
df.to_csv(csv_path, index=False, encoding="utf-8-sig")

print(f"\n{'='*50}")
print(f"HOÀN THÀNH CÀO DỮ LIỆU!")
print(f"Rating đã có : {df['Điểm đánh giá'].notna().sum()}/{len(df)}")
print(f"Shop URL đã có: {df['Shop URL'].notna().sum()}/{len(df)}")
print(f"{'='*50}")
display(df.head())

→ Sẽ crawl 2044 sản phẩm với 6 luồng song song...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i3064932258.html
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i1551219291.html
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i2562394269.html
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i1329853406.html
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i2964031932.html
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2250151368.html
✅ [2] MOLAN Áo phông nam nam ngắn ta | Rating: 4.7 | Shop: MOLAN Shopping Mall
✅ [1] Bộ Đồ Thể Thao Xtep, Bộ Đồ Chạ | Rating: 4.9 | Shop: XTEP Official Store
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [4] Bộ Đồ Lụa Băng Tay Dài Cho Nam | Rating: 4.6 | Shop: Rỗng
✅ [5] Trang phục truyền thống, Bộ qu | Rating: 4.9 | Shop: Kanaya
✅ [0] Jeep Spirit Outdoor Windbreake | Rating: 4.8 | Shop: JEEP SPIRIT Οfficial
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i1069978430.html

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_19616\3244096423.py:155: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4.8' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, "Điểm đánh giá"] = detail["Rating Score"]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_19616\3244096423.py:157: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'JEEP SPIRIT Οfficial' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, "Tên shop"] = detail["Shop Name"]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_19616\3244096423.py:159: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'https://www.lazada.vn/shop/jeep-spirit-fficial/?itemId=2562394269&channelSource=pdp' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, "Shop URL"] = detail["Shop URL"]

[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i3089726635.html
✅ [3] Trang Phục Tay Ngắn Thời Đường | Rating: 4.9 | Shop: Kem Thời Trang
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i1189050599.html
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i1600660988.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i2533489248.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2877387168.html
✅ [6] Trang phục truyền thống, Bộ qu | Rating: 4.8 | Shop: Kanaya
✅ [9] MOLAN Tay ngắn dáng rộng cho N | Rating: 4.8 | Shop: MOLAN Shopping Mall
✅ [7] ÁO DÀI CÁCH TÂN NAM IN HỌA TIẾ | Rating: 4.7 | Shop: Hoàng Kim Anh
✅ [10] Trang Phục Đời Đường Trang Phụ | Rating: 4.8 | Shop: Thời Trang Của Bố
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [8] (NAM LA HÁN Bộ gia đình) Trang | Rating: 5 | Shop: Kanaya
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i2495363900.html
✅ [11] Bộ 3 Áo Thun Thể Thao Nam, Áo  | Rating: 4.9 | Shop: GIABAO SHOP 1596350182
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2174561538.html
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i1386484483.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i2776861542.html
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i3201408096.html
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2350282191.html
✅ [14] Áo quan cổ trang biểu diễn, áo | Rating: 4.9 | Shop: Trang phục đạo cụ biểu diễn Dũng Trum
✅ [12] bn Áo Khoác Thiền Ý Tay Áo Tà  | Rating: 5 | Shop: DSGSDGFHFDH✅ [13] Trang Phục Thời Đường Bộ Đồ Na | Rating: 4.8 | Shop: Thời Trang Của Bố

✅ [16] LUNA Đường trang phục nam Trun | Rating: 4.7 | Shop: LUNA-LH
✅ [17] MPATHW  Áo Hoodie Liền Mũ Thườ | Rating: 5 | Shop: MPATHW MALL
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [15] Quần kaki nam trung niên cao c | Rating: 4.9 | Shop: xưởng sỉ quần áo 1587100905
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i3267081956.html
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i1790971133.html
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2596569377.html
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i2931743182.html
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i1799642777.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i3157726638.html
✅ [20] MEXICO ÁO THUN NAM CAPPA CHẤT  | Rating: 1 | Shop: KAKA MEN
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [21] Bà Ba Nông Dân Nam Bộ - Quần Á | Rating: 4.9 | Shop: KQ SHOP - Quần Áo và Phụ Liệu may mặc
✅ [18] [HCM] Quần áo sinh viên học qu | Rating: 4.8 | Shop: GIAYSYQUAN.COM
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i2720163196.html
✅ [19] CÓ BIGSIZE 4XL Áo tràng phật t | Rating: 4.9 | Shop: Đồ Lam Hồng Phúc An
✅ [22] Quần short Jean Nam  vải jean  | Rating: 4.9 | Shop: Diorgino
✅ [23] STAR FRUIT Quần thường ngày nh | Rating: 4.4 | Shop: STAR FRUIT MALL
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2776064040.html
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i3260670566.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i3121189454.html
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i2507902660.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i13326597735.html
✅ [24] ĐỒ LAM NAM CAO CẤP, LÃNH TỤ TH | Rating: 5 | Shop: Pháp Phục Hoàng Nghĩa
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [28] Năm Trung Niên Và Người Già Na | Rating: 4.7 | Shop: TB supermarket store
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i2623008848.html
✅ [25] Quần Short Nam Thể Thao Cao Cấ | Rating: 4.9 | Shop: LAMANDO
✅ [29] SEA JJT Áo khoác jeans phong c | Rating: 0.0 | Shop: SEA JJT MALL
✅ [26] Áo Tiều Nam (mặc trong) Đạo Ph | Rating: 4.5 | Shop: VinTaNi
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i3139950508.html
✅ [27] Áo Si Quan Bay Đất nam | Rating: 4.4 | Shop: Kho Giày Sĩ Quan
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i2427743465.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i852100758.html
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i1356425180.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i2481407313.html
✅ [30] ĐỒ BỘ THỂ THAO NAM N..Y SÀNH Đ | Rating: 4.8 | Shop: tokyo.shop
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i2179640703.html
✅ [31] Quần short kaki nam thời trang | Rating: 4.8 | Shop: ZUKI shop TH
✅ [32] ÁO KHOÁC HOODIE TRƠN DÂY KÉO S | Rating: 4.5 | Shop: tokyo.shop
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i899216613.html
✅ [34] Bộ quần áo bóng đá, đồ đá banh | Rating: 5 | Shop: BULBAL VIỆT NAM
✅ [35] Quần tây nam công sở trung niê | Rating: 4.7 | Shop: hungphuocfashion
✅ [33] LÃNH TỤ PHỐI NAM Trang phục tr | Rating: 5 | Shop: Kanaya
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i254832834.html
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i3071075638.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i1397590553.html
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2604967288.html
✅ [36] Đồng phục spa, phòng khám màu  | Rating: 5 | Shop: Nguyên ĐP
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i2530889884.html
✅ [37] 【Really Stock】 Bộ Vest Nam Dán | Rating: 4.7 | Shop: ryeytruj
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2451664798.html
✅ [39] [HCM]ÁO THUN NAM CỔ BẺ TAY NGẮ | Rating: 4.9 | Shop: Win 69
✅ [40] Combo quần áo nam quần tây nam | Rating: 4.9 | Shop: Gen Alpha
✅ [41] Áo thun nam cổ tròn 2 màu trắn | Rating: 4.8 | Shop: Quang_thời_trang
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i2931659474.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [38] LIVE GREAT |Áo thun nam tay ng | Rating: 4.9 | Shop: LIVE GREAT
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i941464957.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i2023054480.html
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i1814731041.html
✅ [42] (NAM BA NÚT tay ngắn) Trang ph | Rating: 5 | Shop: Hồng Phúc An
✅ [43] Đồ Lam Đi Chùa # Lãnh Tụ Nam # | Rating: 4.9 | Shop: Đồ Lam Áo Lam
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i2065445859.html
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2247414197.html
✅ [46] [MIỄN PHÍ VẬN CHUYỂN] - ÁO KHO | Rating: 4.5 | Shop: Shop Sale Off
✅ [44] CÓ BIGSIZE 4XL Áo tràng phật t | Rating: 5 | Shop: Đồ Lam Hồng Phúc An
✅ [45] Áo thun dài tay nam thể thao c | Rating: 4.8 | Shop: The DEME Store
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2661639079.html
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i324018264.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [47] áo thun nam đẹp kiểu dáng hàn  | Rating: 4.8 | Shop: kaystore online
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i357982321.html
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i13328763880.html
✅ [48] áo thun nam cổ tròn , áo phông | Rating: 4.9 | Shop: XUZI fashion
✅ [49] Áo Kirkland - Áo Thun Trắng Na | Rating: 5 | Shop: QUẦN SHORT VÁY JEANS
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i1864129734.html
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2314481433.html
✅ [51] BỘ QUẦN ÁO NAM NỮ BC CỔ TRÒN C | Rating: 4.8 | Shop: tokyo.shop
✅ [52] Áo Sơ Mi Nam Tay Dài Hàn Quốc  | Rating: 4.8 | Shop: PONIVALAZA
✅ [50] ÁO KHOÁC HOODIE NAM NỮ CON HẠC | Rating: 4.4 | Shop: tokyo.shop
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2083532360.html
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i2094045097.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i3156509108.html
✅ [53] MPATHW  Áo Sơ Mi Hoa Phong Các | Rating: 5 | Shop: MPATHW MALL
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i974244522.html
✅ [54] Áo thun nam tay dài áo giữ nhi | Rating: 4.9 | Shop: Quần Jean Nam - Vương Nam
✅ [55] Hanlu áo thun cho nam quần áo  | Rating: 4.8 | Shop: Hanlu Style
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i3121310257.html
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [56] Áo thun nam nữ mua xuân Vẽ Mực | Rating: 4.7 | Shop: SHOP VONESA
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i3035822544.html
✅ [57] ÁO KHOÁC HOODIE NAM NỮ DONT ST | Rating: 4.5 | Shop: Dubaishop
✅ [58] (Hàng loại 1) Bộ Quần Áo Sơ Mi | Rating: 5 | Shop: Tổng Kho Đồ Nam ( chuyên sỉ lẻ )
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i693772195.html
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2233985477.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i941530098.html
✅ [59] ÁO KHOÁC HOODIE NAM NỮ UNISEX  | Rating: 4.6 | Shop: tokyo.shop
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i3268342820.html
[Luồng 0] ⚠️ PHÁT HIỆN BOT! Vui lòng tự giải Captcha trên cửa sổ 0...
✅ [60] (MA87) Pháp phục đi chùa THUKE | Rating: 5 | Shop: Pháp phục thu kẹo
✅ [61] ÁO NỈ, ÁO KHOÁC HOODIE ĐEN SIÊ | Rating: 4.4 | Shop: tokyo.shop
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i2574615464.html
✅ [62] ĐỒ BỘ THỂ THAO DONT STOP TRÀ S | Rating: 4.7 | Shop: Dubaishop
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [64] [MIỄN PHÍ VẬN CHUYỂN] - ÁO KHO | Rating: 4.5 | Shop: Shop Sale Off
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i1262788779.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i386658098.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i2230405978.html
✅ [65] Áo thun tay dài cổ cao nam thu | Rating: 5 | Shop: Avan Fashion
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i2729997759.html
[Luồng 2] ⚠️ PHÁT HIỆN BOT! Vui lòng tự giải Captcha trên cửa sổ 2...
✅ [66] Áo Đũi nam cộc tay - Áo sơ mi  | Rating: 4.8 | Shop: Gia Lộc Officall
✅ [67] ĐỒ BỘ THỂ THAO HOA VĂN CHỮ NHẬ | Rating: 4.5 | Shop: tokyo.shop
✅ [68] HCM ÁO THUN 3 LỖ NAM , SÁT NÁC | Rating: 4.8 | Shop: GYM PT68 stores
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i3216133757.html
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2635902145.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2520906029.html
✅ [70] Bộ đũi thô dài tay nam trung n | Rating: 5 | Shop: Laddy Mall
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i2233994476.html
[Luồng 0] ❌ Quá 60s không giải được.
✅ [71] (QUÀ LÀ GÓI DẦU GỘI TỪ SHOP CH | Rating: 5.0 | Shop: xuongniTNT
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i1878808054.html
✅ [72] Áo thun thể dục cổ bẻ và cổ tr | Rating: 4.9 | Shop: Shop mẹ Tiger.
✅ [73] Trang Phục Biểu Diễn Halloween | Rating: 4.5 | Shop: TAO Anime
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i1870023238.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i3010314180.html
✅ [74] ĐỒ BỘ THỂ THAO DONT STOP TRÀ S | Rating: 4.8 | Shop: Dubaishop
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [63] [HCM]áo thun nam trơn cổ tròn  | Rating: 4.1 | Shop: Thời Trang BULL KID
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i2347390692.html
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i2106722307.html
[Luồng 2] ❌ Quá 60s không giải được.
✅ [75] ÁO THUN NAM , ÁO BA LỔ NAM , Á | Rating: 4.9 | Shop: T&T08_store
✅ [76] Bộ Quần Áo Đũi Nam Dài Cổ bẻ c | Rating: 4.5 | Shop: shop x men
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i2106671628.html
✅ [77] Áo Phong Cách Trung Hoa Mùa Hè | Rating: 5 | Shop: TB FASHION STORE
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2931691406.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2640160188.html
✅ [78] Đồ Lam Đi Chùa La Hán Cho Nam  | Rating: 4.8 | Shop: TamLinhNgocBao
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [79] Áo sơ mi nam dài tay Phối Đồ H | Rating: 4.6 | Shop: shop x men
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i3194885936.html
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [69] Quần nỉ nam, Quần nỉ bông nam  | Rating: 4.8 | Shop: Platinum Menswear
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i2106554916.html
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i845508153.html
✅ [80] Áo sơ mi nam dài tay Phối Đồ H | Rating: 4.7 | Shop: shop x men
✅ [81] CÓ BIGSIZE 4XL Áo tràng phật t | Rating: 5 | Shop: Đồ Lam Hồng Phúc An
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i2366314434.html
✅ [82] Áo Khoác Dù Nam Cổ Bẻ Phối Khó | Rating: 4.3 | Shop: Hoài Thương Fashion MALL
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2195318921.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i229246116.html
✅ [83] JIFANPAUL | Áo Khoác Nam Nhẹ C | Rating: 4.6 | Shop: JIFANPAUL Global
✅ [84] Áo sơ mi nam dài tay Phối Đồ H | Rating: 4.8 | Shop: shop x men
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i2042546244.html
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i2397866779.html
✅ [85] ĐỒ BỘ THỂ THAO HOA VĂN CHỮ NHẬ | Rating: 4.4 | Shop: Dubaishop
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i2669020123.html
✅ [87] ĐỒ BỘ THỂ THAO CHỮ DONT .STOP  | Rating: 4.7 | Shop: Dubaishop
✅ [86] Áo Thun Ba Lỗ Nam HAHAMAN Cott | Rating: 4.8 | Shop: HAHAMAN
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i1883862045.html
✅ [88] [HCM]Áo Thun Nam Dài Tay Mẫu M | Rating: 4.7 | Shop: Win 69
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i1041164028.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i1402582985.html
✅ [89] ÁO THUN NAM TAY DÀI THU ĐÔNG M | Rating: 4.9 | Shop: Win 69
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i2166301296.html
✅ [90] Áo thun nam big size 110kg 5XL | Rating: 4.5 | Shop: BigsizeSG
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i2608858742.html
✅ [91] Áo Polo POLOMAN 15 nam nhiều m | Rating: 4.9 | Shop: Poloman Official1
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i1869827869.html
✅ [92] ĐỒ LAM ĐI CHÙA - ÁO TRÀNG PHẬT | Rating: 4.8 | Shop: đồ lam đi chùa giá sỉ
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i3064860055.html
✅ [94] ÁO SWEATER UNISEX TRƠN (NHIỀU  | Rating: 4.8 | Shop: KaChuch
✅ [93] ĐỒ BỘ THỂ THAO ATAGO NÚI PHÚ S | Rating: 4.1 | Shop: Dubaishop
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] đang truy cập URL: https://www.lazada.vn/products/pdp-i2416761377.html
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [95] Áo thun Unisex Oversize Cotton | Rating: 4.8 | Shop: LWSTORE
[Luồng 5] đang truy cập URL: https://www.lazada.vn/products/pdp-i2268318011.html
✅ [96] Áo Thun Polo Nam Nữ Cổ Trụ Tay | Rating: 4.8 | Shop: Win 69
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] đang truy cập URL: https://www.lazada.vn/products/pdp-i1740581779.html
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] đang truy cập URL: https://www.lazada.vn/products/pdp-i2091973514.html
✅ [97] Bộ Đồ Ngủ Nam Nữ Khủng Long Độ | Rating: 4.9 | Shop: Rubylong
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] đang truy cập URL: https://www.lazada.vn/products/pdp-i2997583901.html
✅ [98] Áo thun ngắn tay của nam giới  | Rating: 5 | Shop: Men's Fashion Home
✅ [99] Áo thể thao Cầu lông, Pickleba | Rating: 5 | Shop: ĐỒ THỂ THAO KIM PHÚC
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] đang truy cập URL: https://www.lazada.vn/products/pdp-i1453605042.html
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [100] LIVE GREAT   quần tây nam dài  | Rating: 4.9 | Shop: LIVE GREAT

,ID Sản phẩm,Tên sản phẩm,Danh mục,Giá,Giảm giá,Đã bán,Điểm đánh giá,Lượt đánh giá,Địa điểm,Đường dẫn,Hình ảnh,Tên shop,Shop URL
0,2562394269,Jeep Spirit Outdoor Windbreaker Clothing Men's...,Trang phục nam,269.999 ₫,51% Off,1.9K Đã bán,4.8,753.0,Thành phố Hồ Chí Minh,https://www.lazada.vn/products/pdp-i2562394269...,https://img.lazcdn.com/g/p/6199d4f39b850a5a986...,JEEP SPIRIT Οfficial,https://www.lazada.vn/shop/jeep-spirit-fficial...
1,1329853406,"Bộ Đồ Thể Thao Xtep, Bộ Đồ Chạy Bộ Hai Mảnh Nh...",Trang phục nam,495.280 ₫,47% Off,550 Đã bán,4.9,207.0,China,https://www.lazada.vn/products/pdp-i1329853406...,https://img.lazcdn.com/g/p/a3467728107f63b3090...,XTEP Official Store,https://www.lazada.vn/shop/xtep-official-store...
2,3064932258,MOLAN Áo phông nam nam ngắn tay thể thao cổ tr...,Trang phục nam,38.000 ₫,50% Off,331 Đã bán,4.7,80.0,China,https://www.lazada.vn/products/pdp-i3064932258...,https://img.lazcdn.com/g/p/becc8492da7c50d2daa...,MOLAN Shopping Mall,https://www.lazada.vn/shop/molan-shopping-mall...
3,2250151368,"Trang Phục Tay Ngắn Thời Đường, Bộ Đồ Nam Chất...",Trang phục nam,212.430 ₫,33% Off,822 Đã bán,4.9,268.0,Ninh Bình,https://www.lazada.vn/products/pdp-i2250151368...,https://img.lazcdn.com/g/p/a71cbab85bdc3c27dc1...,Kem Thời Trang,https://www.lazada.vn/shop/kem-thoi-trang/?ite...
4,2964031932,Bộ Đồ Lụa Băng Tay Dài Cho Nam Mùa Xuân Hè Tập...,Trang phục nam,190.800 ₫,10% Off,288 Đã bán,4.6,28.0,China,https://www.lazada.vn/products/pdp-i2964031932...,https://img.lazcdn.com/g/ff/kf/Sd156b66e555c42...,,https://www.lazada.vn/shop/lazada-global/?item...

In [1]:
import time
import re 
from bs4 import BeautifulSoup
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from concurrent.futures import ThreadPoolExecutor
import threading
import queue
import pandas as pd
import random
import winsound  
import os

# 1. TẢI FILE CSV HIỆN TẠI VÀO PHÂN TÍCH
csv_path = os.path.join("data", "lazada_trang_phuc_nam.csv")
df = pd.read_csv(csv_path)

# 2. XÁC ĐỊNH CÁC SẢN PHẨM BỊ THIẾU THÔNG TIN
# Bao gồm cả bị NaN (trống dữ liệu) hoặc là bị chuỗi trống ""
missing_mask = (df['Điểm đánh giá'].isna()) | (df['Điểm đánh giá'] == "") | (df['Shop URL'].isna()) | (df['Shop URL'] == "")
df_missing = df[missing_mask].copy()

# ===================== CẤU HÌNH =====================
MAX_WORKERS = 6

print(f"→ Sẽ crawl vá lỗi cho {len(df_missing)} sản phẩm bị thiếu với {MAX_WORKERS} luồng song song...")

# 3. CHUẨN BỊ ĐA LUỒNG
profile_queue = queue.Queue()
for i in range(MAX_WORKERS):
    profile_queue.put(i)

chrome_init_lock = threading.Lock()

def crawl_lazada_product(url):
    profile_id = profile_queue.get()
    extracted_data = {}
    driver = None
    
    try:
        print(f"[Luồng {profile_id}] 🔄 Đang khởi tạo trình duyệt Chrome...")
        options = uc.ChromeOptions()
        options.add_argument('--disable-gpu')
        options.add_argument('--window-size=1920,1080')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        
        # MỖI LUỒNG DÙNG 1 FOLDER PROFILE KHÁC NHAU
        profile_path = rf'C:\Users\ADMIN\ChromeProfileData_{profile_id}'
        options.add_argument(f'--user-data-dir={profile_path}')
        
        with chrome_init_lock:
            driver = uc.Chrome(options=options)
            
        driver.get(url)
        
        # --- CƠ CHẾ KIỂM TRA ĐỂ VƯỢT CAPTCHA ---
        time.sleep(3)
        if "we need to check if you are a robot" in driver.page_source.lower() or "recaptcha" in driver.page_source.lower() or "bảo vệ bởi ddos" in driver.page_source.lower():
            print(f"[Luồng {profile_id}] ⚠️ PHÁT HIỆN BOT! Vui lòng tự giải Captcha trên cửa sổ {profile_id}...")
            
            try:
                for _ in range(5):
                    winsound.Beep(1500, 500) 
                    time.sleep(0.1)
            except:
                pass

            try:
                WebDriverWait(driver, 60).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'pdp-mod-review'))
                )
                print(f"[Luồng {profile_id}] ✅ Đã qua bước xác minh.")
            except Exception:
                print(f"[Luồng {profile_id}] ❌ Quá 60s không giải được.")
        
        # Chờ load trang
        try:
            WebDriverWait(driver, 15).until(EC.presence_of_element_located((By.CLASS_NAME, 'pdp-mod-review')))
            driver.execute_script("window.scrollBy(0, 800);")
            time.sleep(4)
            driver.execute_script("window.scrollBy(0, 1000);")
            time.sleep(2)
        except Exception:
            pass
        
        # Trích xuất HTML
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')
        
        # 1. TÊN SHOP VÀ LINK SHOP
        seller_element = soup.select_one('.seller-name-v2__detail-name, .seller-name-v2__top a, .seller-name__detail')
        if seller_element:
            extracted_data['Shop Name'] = seller_element.get_text(strip=True)
            link = seller_element.get('href')
            if not link and seller_element.find_parent('a'):
                link = seller_element.find_parent('a').get('href')
            extracted_data['Shop URL'] = "https:" + link if link and link.startswith('//') else (link or "")
        else:
            extracted_data['Shop Name'] = ""
            extracted_data['Shop URL'] = ""
            
        # 2. ĐÁNH GIÁ TRUNG BÌNH
        score_tag = soup.select_one('.container-star-v2-score, .score-average, .score, .rating-score, .pdp-review-summary__stars')
        if score_tag:
            extracted_data['Rating Score'] = score_tag.get_text(strip=True)
        else:
            all_text = ' '.join(soup.stripped_strings)
            score_regex = re.search(r'(\d\.\d)\s*\(\d+\)', all_text)
            extracted_data['Rating Score'] = score_regex.group(1) if score_regex else ""
            
    except Exception as e:
        print(f"[Luồng {profile_id}] ❌ Lỗi khi thao tác với Chrome: {e}")
    finally:
        try:
            if driver:
                driver.quit()
        except:
            pass
        profile_queue.put(profile_id)
        
    return extracted_data

# ===================== QUẢN LÝ CHẠY VÀ GHI DỮ LIỆU LẠI VÀO DF =====================
def crawl_one(args):
    idx, row = args
    url = row["Đường dẫn"]
    
    if pd.isna(url):
        return idx, None
    
    time.sleep(random.uniform(1, 4)) 
    
    detail = crawl_lazada_product(url)
    if detail:
        print(f"✅ [{idx}] {row['Tên sản phẩm'][:30]} | Rating: {detail.get('Rating Score') or 'Rỗng'} | Shop: {detail.get('Shop Name') or 'Rỗng'}")
    return idx, detail

# Thực thi đa luồng nếu có sản phẩm thiếu
if not df_missing.empty:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = executor.map(crawl_one, df_missing.iterrows())
        
        for idx, detail in futures:
            if detail is None or not detail:
                continue
            if "Rating Score" in detail and pd.notna(detail["Rating Score"]) and detail["Rating Score"] != "":
                df.at[idx, "Điểm đánh giá"] = detail["Rating Score"]
            if "Shop Name" in detail and pd.notna(detail["Shop Name"]) and detail["Shop Name"] != "":
                df.at[idx, "Tên shop"] = detail["Shop Name"]
            if "Shop URL" in detail and pd.notna(detail["Shop URL"]) and detail["Shop URL"] != "":
                df.at[idx, "Shop URL"] = detail["Shop URL"]

    # LƯU FILE CHÈN LẠI VÀO BẢN GỐC
    df.to_csv(csv_path, index=False, encoding="utf-8-sig")

print(f"\n{'='*50}")
print(f"HOÀN THÀNH QUÉT VÀ VÁ DỮ LIỆU!")
print(f"Rating đã có : {df['Điểm đánh giá'].notna().sum()}/{len(df)}")
print(f"Shop URL đã có: {df['Shop URL'].notna().sum()}/{len(df)}")
print(f"{'='*50}")
display(df.head())

→ Sẽ crawl vá lỗi cho 382 sản phẩm bị thiếu với 6 luồng song song...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [324] Đồ bộ quần áo nam mùa hè cổ bẻ | Rating: 5 | Shop: PAHITO VIỆT NAM
✅ [354] Trang Phục Hanfu Cổ Trang Phục | Rating: Rỗng | Shop: TB FASHION STORE
✅ [227] Áo Thun Tay Ngắn Cotton Nguyên | Rating: Rỗng | Shop: TB FASHION STORE
✅ [323] Áo thể thao Cầu lông, Pickleba | Rating: 4.9 | Shop: ĐỒ THỂ THAO KIM PHÚC
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [303] Áo Ba Lỗ Cotton Dệt Kim Rộng R | Rating: Rỗng | Shop: TB FASHION STORE
✅ [246] Quần Áo Làm Việc Đầu Bếp Dài T | Rating: Rỗng | Shop: TAO Men's Fashion Collections

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_29904\3413638453.py:150: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4.9' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, "Điểm đánh giá"] = detail["Rating Score"]

[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [358] Áo Thun Nam Tay Ngắn Nhanh Khô | Rating: Rỗng | Shop: TB FASHION STORE
✅ [372] Bộ Đồ Thể Thao Mùa Hè Ice Silk | Rating: 5 | Shop: TB FASHION STORE
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [363] Áo Sơ Mi Tay Ngắn Mùa Hè Thườn | Rating: Rỗng | Shop: TB FASHION STORE
✅ [374] Áo Khoác Mùa Đông Dày Có Lớp C | Rating: 5 | Shop: Kawadu
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...✅ [375] Lansboter áo blazer nam bộ ves | Rating: 4.9 | Shop: Lansboter

[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...✅ [373] Quần short lửng nam kaki jean  | Rating: 5 | Shop: Mộc Jean - Quần jean nam xuất xịn

[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [376] Áo Thun Nam Mùa Hè Mới Ngoài T | Rating: 3 | Shop: TB supermarket store
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [377] đồ bộ đi chùa nam,3 nút kate | Rating: 5 | Shop: shop đồ lam đi chùa giá sỉ
✅ [378] CÓ BIGSIZE 3XL Áo tràng phật t | Rating: 5 | Shop: Đồ Lam Hồng Phúc An
✅ [379] Bộ Đồ Tu Tập Phật Giáo Cho Nam | Rating: 5 | Shop: TB FASHION STORE
✅ [380] Bộ Áo Sơ Mi Nửa Tay Nam Cotton | Rating: 4.6 | Shop: TAO Handsome Apparel
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [381] Yonex Mới Áo Nỉ Nam Full Thăng | Rating: 5 | Shop: 3D clothing
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [382] [FREESHIP] Áo Khoác Dù Nam Cổ  | Rating: 4.2 | Shop: Màu Tím Fashion
✅ [385] Áo Choàng Kimono Nam Màu Đen T | Rating: 4.7 | Shop: Global Merch Park
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [384] Happybuyner Thời Trang Mùa Hè  | Rating: 4.3 | Shop: happybuyner
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [383] JIFANPAUL | Áo Khoác Nam Đệm D | Rating: 4.5 | Shop: JIFANPAUL Global
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [386] Áo Khoác Dày & Ấm Thêu Tay Khô | Rating: 5 | Shop: Kawadu
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [387] MAIYING | Bộ Com Lễ Phục Cho P | Rating: 4.5 | Shop: Maiying
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [389] JIFANPAUL | Bộ Đồ Thể Thao Nha | Rating: 4.7 | Shop: JIFANPAUL Global
✅ [388] Lansboter áo blazer nam bộ ves | Rating: 5 | Shop: Lansboter
✅ [390] JIFANPAUL | Áo Khoác Nam Size  | Rating: 4.5 | Shop: JIFANPAUL Global
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [393] Áo Thun Nam Mùa Hè Ngoài Trời  | Rating: 5 | Shop: TB supermarket store
✅ [391] {Tặng liễng cài áo} Áo da | Rating: 5 | Shop: Áo dài cách tân giá tốt
✅ [392] Bộ Áo Hoodie Mùa Đông Nam Màu  | Rating: 5 | Shop: GlobalTechMart
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [394] LOFU JOEY | Áo Khoác Nam Cỡ Lớ | Rating: 5 | Shop: Lofu Joey Clothing
✅ [396] JIFANPAUL | Áo Khoác Mỏng Phon | Rating: 4.3 | Shop: JIFANPAUL Global
✅ [395] Ấm cúng lên thời trang cá tính | Rating: 5 | Shop: Cozy Up
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [397] Bộ vets nam trung niên vest đư | Rating: 4.9 | Shop: VEST TRUNG NIÊN CAO CẤP
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [398] JIFANPAUL | Áo Khoác Nam Có Cổ | Rating: 4.7 | Shop: JIFANPAUL Global
✅ [399] Bộ Quần Áo Nam Ngắn Tay Phối H | Rating: 5 | Shop: King Man Boutique
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [400] Stone islandˉhuy hiệu dáng rộn | Rating: 5 | Shop: 520 store
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [401] JIFANPAUL | Áo Hoodie Lông Cừu | Rating: 4.9 | Shop: JIFANPAUL Global
✅ [402] JIFANPAUL | Áo Sơ Mi Dài Tay T | Rating: 5 | Shop: JIFANPAUL Global
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [403] JIFANPAUL | Áo Khoác Nam Cotto | Rating: 5 | Shop: JIFANPAUL Global
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [404] Áo Cardigan Nam Len Mỏng Thời  | Rating: 4.7 | Shop: Kawadu
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [405] Áo Sơ Mi Nam Váy Kẻ Sọc Dài Ta | Rating: 5 | Shop: KK GEEZER Official Store
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [406] Áo Khoác Thanh Lịch Cổ Trụ Dàn | Rating: 4.4 | Shop: Kawadu
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [407] (Hàng loại 1) Bộ Quần Áo Sơ Mi | Rating: 5 | Shop: Tổng Kho Đồ Nam ( chuyên sỉ lẻ )
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [408] Quần Áo Nam - Bộ quần Áo Nam i | Rating: 4.9 | Shop: minmouse01
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [409] Đồ Lam Đi Chùa # Mẫu La Hán Cú | Rating: 4.1 | Shop: Shop mỡ mỡ
✅ [410] Bộ quần áo vest nam kèm phụ ki | Rating: 4.7 | Shop: Nhang Đèn Nga Nguyễn
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [411] Áo dài nam truyền thống xưa tứ | Rating: 4.6 | Shop: Hoàng Kim Anh
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [412] Bộ quần áo dài tay cho bố trun | Rating: 5 | Shop: quanaotrungnien
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [413] Quần kaki dài nam ZA.RA ,5 màu | Rating: 4.8 | Shop: Gen Alpha
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [414] MPATHW  Bộ áo sơ mi ngắn tay h | Rating: 5 | Shop: MPATHW MALL
✅ [415] Áo sơ mi cổ điển người đàn ông | Rating: 4.5 | Shop: Oufisun Fashion Clothing
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [417] Bộ Đồng Phục Bảo Hộ Lao Động M | Rating: 4.5 | Shop: TAO Men's Fashion Collections
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [416] [Hàng mới về] Áo thể thao nam  | Rating: 4.9 | Shop: HMSPORT DESIGN
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [418] Pierre Cardin | Áo Khoác Nam T | Rating: 5 | Shop: Pierre Cardin Global
✅ [419] Bộ vest nam trung niên chất l | Rating: 4.9 | Shop: Vest Nam Trung Niên
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [420] Áo Cardigan Có Khóa Kéo, Màu T | Rating: 4.3 | Shop: Men's Fashion Home
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [421] Áo Khoác Nam Thời Trang Công S | Rating: 4.9 | Shop: Kawadu
✅ [422] Áo Sweater Len Nam Mùa Thu Đôn | Rating: 5 | Shop: Kawadu
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [423] Thời trang người đàn ông Bộ đồ | Rating: 4.4 | Shop: Supper Cai
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [424] Áo dài nam cách tân form vestt | Rating: 5 | Shop: Áo Dài Chaang May
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [425] Áo dài cách tân Nam họa tiết T | Rating: 4.9 | Shop: Áo Dài Hoàng Mai - Áo Dài Cao Cấp
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [426] Áo Khoác Nam Kawadu Bông Dày Ấ | Rating: 4.8 | Shop: Kawadu
✅ [427] Áo Dài Cách Tân Nam Chất Liệu  | Rating: 5 | Shop: Jogger Pants sài gòn
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [428] Áo Khoác Đông Ấm Áp cho Nam Tr | Rating: 5 | Shop: Kawadu
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [429] Áo dài cách tân Nam thiết kế t | Rating: 5 | Shop: Áo Dài Chaang May
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [430] Bộ Đồ Thể Thao Nam Hai Mảnh Mù | Rating: 5 | Shop: TB FASHION STORE
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [433] CHAFEI | Áo Khoác Nỉ Có Mũ Đín | Rating: 4.9 | Shop: Pengruicheng
✅ [431] Áo dài cách tân Nam - chất liệ | Rating: 5 | Shop: aodai_phapphuclinhson
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [432] Hanfu Chính Hãng Trang Phục Cổ | Rating: 5 | Shop: Always shining
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [434] Áo Thun Nam Tay Dài Có Cổ Bẻ,  | Rating: 4.5 | Shop: MEN'STIAKON men's clothing
✅ [435] Mens Chinese Style Hemp Shirt  | Rating: 5 | Shop: crccez
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [436] Quần Áo Lính Cổ Đại Trung Quốc | Rating: 5.0 | Shop: TB FASHION STORE
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [437] Bộ quần áo mặc nhà cho ông, ch | Rating: 5 | Shop: quanaotrungnien
✅ [438] Bộ áo bà ba nam nâu truyền thố | Rating: 4.8 | Shop: aodaiaobaba
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [439] LUNA Quần áo nam  Áo thun nam  | Rating: 5 | Shop: LUNA-LH
✅ [441] Bộ Áo Thun Ngắn Tay Mùa Hè Ice | Rating: 5 | Shop: TB FASHION STORE
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [440] Bộ Quần Ấu và Áo Sơ Mi Nam dàn | Rating: 5 | Shop: THUÝ NGÂN THỜI TRANG NAM
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [442] Áo thun hoạ tiết Cờ mỹ thêu xù | Rating: 5 | Shop: MonStore18
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [443] Lansboter áo hodie áo khoác ho | Rating: 5 | Shop: Lansboter
✅ [444] (Form Tôn Vai) Áo Sơ Mi SILAS  | Rating: 5 | Shop: SILAS STUDIO
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [445] Áo Khoác Dạ Nam Cao Cấp Phong  | Rating: 5 | Shop: Kawadu
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [446] JIFANPAUL | Áo Khoác Nam Dày Ấ | Rating: 5 | Shop: JIFANPAUL Global
✅ [447] Áo khoác cardigan dệt kim bốn  | Rating: 4.9 | Shop: Kawadu
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [448] JIFANPAUL | Áo Khoác Nam Dành  | Rating: 4.6 | Shop: JIFANPAUL Global
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [449] Áo Thun Nam Mùa Hè Thể Thao Ta | Rating: 5 | Shop: TB FASHION STORE
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...✅ [450] JIFANPAUL | Quần Dài Thể Thao  | Rating: 4.8 | Shop: JIFANPAUL Global

✅ [451] GK|Áo Sweater Nam Kiểu Hàn Quố | Rating: 5 | Shop: Kawadu
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [453] Áo Vest Câu Cá Thường Ngày Cho | Rating: 5 | Shop: Rỗng
✅ [452] Bộ Đồ Thể Thao Ice Silk Cho Na | Rating: 5 | Shop: Rỗng
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [454] Áo Nỉ Dày Màu Xám Mỹ Dành Cho  | Rating: Rỗng | Shop: TB FASHION STORE
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [456] Quần Jean Nam Trung Niên Dáng  | Rating: 4.8 | Shop: Quần Áo Nam Trung Niên
✅ [455] JIFANPAUL | Áo Hoodie Len Mềm  | Rating: 3.3 | Shop: JIFANPAUL Global
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [457] JIFANPAUL | Áo Hoodie Nam Lót  | Rating: 4.7 | Shop: JIFANPAUL Global
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [458] Quần Thể Thao Nam Mùa Xuân Hè  | Rating: 5 | Shop: TAO Men's Fashion Collections
✅ [459] Áo Thun Nam Chiến Thuật Quân S | Rating: 4.9 | Shop: GlobalLifestyle
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [460] Áo Khoác Nỉ Trùm Đầu Có Khóa K | Rating: 5 | Shop: Rỗng
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [462] Bộ Đồ Thể Thao Nam Thường Ngày | Rating: 5 | Shop: TB FASHION STORE
✅ [461] Áo Thun Nam Tay Dài Mùa Xuân T | Rating: Rỗng | Shop: Rỗng
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [463] Cổ tròn mới tay ngắn vải cotto | Rating: 4.9 | Shop: FZWSED SHOP
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [465] [HCM]Nhiều màu đẹp - Bộ đũi na | Rating: 5 | Shop: Win 69
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [464] Quần Áo Song Sinh Zhuang Dành  | Rating: 0.0 | Shop: TB Men's Style leader
✅ [466] AP67 Áo Thun Thể Dục Cổ Tròn,  | Rating: 5 | Shop: An Phu Fashion
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [468] Bộ quần áo xanh ô lưu dài tay  | Rating: 5 | Shop: An Nhiên - Đồ lính
✅ [467] Nguyên Chất Cotton, Vải Bông B | Rating: 5 | Shop: TB supermarket store
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [469] DIESEL nam cotton thường ngày  | Rating: 4.6 | Shop: CleaceStore57re7
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [470] Áo trường sam 7 vạt - áo đi đư | Rating: 5 | Shop: Văn Hóa Phẩm Phật Giáo Diệu Phước
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [472] [IN ÁO] Áo thun Cuộc đời người | Rating: 4.8 | Shop: ÁO SIÊU CHẤT
✅ [471] Áo thun tay dài cổ cao nam thu | Rating: 5 | Shop: Avan Fashion
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [474] (HOT) Áo Thun Nam Cổ Tròn Phối | Rating: 5 | Shop: THOITRANGNAM1986
✅ [473] Áo Khoác Hoodier Cặp Đôi In Hì | Rating: 4.3 | Shop: Thời _Trang _Thiên_Khải
✅ [475] Wilson Chất Lượng Cao Người Đà | Rating: 5 | Shop: x5tj
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [476] vest nam 6 khuy , bộ vest nam  | Rating: 5 | Shop: Poroman luxury
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [477] Áo Thun Cổ Tròn Nam COTON Vải  | Rating: 4.9 | Shop: NATO - OfficialStore
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [479] Áo Thun Nam Tay Ngắn Ice Silk  | Rating: 5 | Shop: TB FASHION STORE
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [481] [FREESHIP MAX] - Áo Sơ Mi Nam  | Rating: 5 | Shop: An Phu Fashion
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [482] Áo Thun Chạy Bộ Dài Tay Nam, Á | Rating: 5 | Shop: GlobalTechMart
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [478] Áo Khoác Cardigan Trùm Đầu Rộn | Rating: 5 | Shop: Rỗng
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [484] Áo Sơ Mi Nam Tay Dài Cotton Ng | Rating: Rỗng | Shop: Rỗng
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [480] Áo Nỉ Nam 2024 Mới Thu Đông Dà | Rating: 4.9 | Shop: TB FASHION STORE
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [485] Áo Thun Thể Thao Nam Mùa Thu Đ | Rating: Rỗng | Shop: Rỗng
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [486] Bộ Thể Thao Nam Viền Chất Tổ O | Rating: 5 | Shop: MINHSTORE66 Xưởng Thời Trang
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [483] Áo Khoác Len Nam Kiểu Dáng Thể | Rating: Rỗng | Shop: GlobalWonderShop
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [488] Áo Nỉ Lót Lông Cừu Lụa Vàng Na | Rating: 3.9 | Shop: Rỗng
✅ [489] Áo phông cộc tay nam nữ Áo ph | Rating: 4.8 | Shop: THỜI TRANG HOTTREN 693
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [491] JIFANPAUL | Áo Khoác Len Dày c | Rating: 5 | Shop: JIFANPAUL Global
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [492] Mens chiến thuật Hoodies quân  | Rating: 4.9 | Shop: Global Merch Park
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [487] Áo Hoodie Dày Lót Lông Cừu Thờ | Rating: 5 | Shop: Rỗng
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [494] YOULIN | Áo Polo Sang Trọng &  | Rating: 5 | Shop: Men Fashion Concept Store
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [490] Lacepulse丨 người đàn ông của á | Rating: 4.5 | Shop: Lacepulse Store
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [495] Thoáng Khí Trọng Lượng Nhẹ Khô | Rating: 5 | Shop: bewan6274
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [496] Áo khoác nam phong cách Nhật r | Rating: 4.8 | Shop: Kawadu
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [498] Bộ Đồ Cotton Lanh Thường Ngày  | Rating: 4.3 | Shop: Rỗng
✅ [493] Áo Nỉ Nam Dài Tay Rộng Rãi Có  | Rating: Rỗng | Shop: Rỗng
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [499] Áo Sơ Mi Nam Cổ Đứng Cỡ Lớn Ph | Rating: 4.7 | Shop: TB FASHION STORE
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [500] Áo Sơ Mi Lụa Nam Mùa Hè Cổ Đứn | Rating: 5 | Shop: Rỗng
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [501] Áo sơ mi nam dài tay Phối Đồ H | Rating: 4.6 | Shop: shop x men
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [497] Áo Sơ Mi Tay Ngắn Ice Silk Dàn | Rating: 5 | Shop: TAO Handsome Apparel
✅ [503] LIVE GREAT |2025 ngắn tay Mới  | Rating: 4.9 | Shop: LIVE GREAT
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [502] Jeanswest | Áo Khoác Thời Tran | Rating: 5 | Shop: Men Fashion Concept Store
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [504] Áo thun ngắn tay in nam vải co | Rating: 5 | Shop: CohesiveStore60re3
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [505] Mexican | Áo Khoác Chống Nắng  | Rating: 4.8 | Shop: MEXICAN outdoor sports
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [506] FANWUJINHUANG | Áo polo cổ bẻ  | Rating: 4.9 | Shop: FanYuJinHuang
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [507] JIFANPAUL | Áo Khoác Mỏng Phon | Rating: 4.8 | Shop: JIFANPAUL Global
✅ [508] JIFANPAUL | Áo Khoác Nam Thu/Đ | Rating: 4.7 | Shop: JIFANPAUL Global
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [509] Quần Áo Quân Sự Chiến Thuật, Á | Rating: 4.9 | Shop: YINZI STORE
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [510] Bộ Đồ Thể Thao Nam Gồm Áo Hood | Rating: 4.9 | Shop: GlobalSuperBazaar
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [511] Pierre Cardin | Áo Polo Tay Ng | Rating: 4.8 | Shop: Pierre Cardin Global
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [512] Áo Len Nam Dáng Ôm, Nhẹ, Cổ Gi | Rating: 4.8 | Shop: GlobalTechMart
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [513] JIFANPAUL | Áo Thun Cổ Tròn Ta | Rating: 4.9 | Shop: JIFANPAUL Global
✅ [514] JIFANPAUL | Áo Khoác Nỉ Dày Có | Rating: 5 | Shop: JIFANPAUL Global
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [515] Lansboter áo blazer nam bộ ves | Rating: 5 | Shop: Lansboter
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [516] Áo Vest Nam Thời Trang Phong C | Rating: 5 | Shop: Kawadu
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [517] Áo Thun Tay Dài Có Sọc Cổ V Th | Rating: 4.2 | Shop: Kawadu
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [518] Clemine  Áo Khoác Len Nam Áo K | Rating: 0.0 | Shop: Clemine Mall
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [520] Áo Khoác Chống Gió Cổ Đứng Thu | Rating: 5 | Shop: Kawadu
✅ [519] JIFANPAUL | Trang Phục Hanfu T | Rating: 5 | Shop: JIFANPAUL Global
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [521] JIFANPAUL | Áo Khoác Cổ Đứng P | Rating: 5 | Shop: JIFANPAUL Global
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [522] Áo Hoodie Nam Nữ WALKUPTREND U | Rating: 5 | Shop: HOTTREND FASHION
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [523] Áo Thun Dài Tay Mỏng Có Mũ Trù | Rating: 4.5 | Shop: Kawadu
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [524] Áo Khoác Nam Thời Trang Dễ Dàn | Rating: 5 | Shop: Kawadu
[Luồng 2] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [525] Áo Thun Tay Ngắn Cổ Tròn Dáng  | Rating: 4.6 | Shop: Rỗng
✅ [526] JIFANPAUL | Áo Khoác Dày Ấm ch | Rating: 5 | Shop: JIFANPAUL Global
[Luồng 4] 🔄 Đang khởi tạo trình duyệt Chrome...
[Luồng 3] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [527] Áo Sơ Mi Tay Ngắn Nam Vải Lụa  | Rating: 5 | Shop: TB FASHION STORE
[Luồng 0] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [528] Áo đi chùa nam - Áo nâu phật t | Rating: 5 | Shop: aodaiaobaba
[Luồng 5] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [529] ĐỒ BỘ THỂ THAO NAM N..Y SÀNH Đ | Rating: 4.5 | Shop: tokyo.shop
[Luồng 1] 🔄 Đang khởi tạo trình duyệt Chrome...
✅ [530] Bộ áo bà ba nam màu đen truyền | Rating: 5 | Shop: aodaiaobaba

,ID Sản phẩm,Tên sản phẩm,Danh mục,Giá,Giảm giá,Đã bán,Điểm đánh giá,Lượt đánh giá,Địa điểm,Đường dẫn,Hình ảnh,Tên shop,Shop URL
0,2562394269,Jeep Spirit Outdoor Windbreaker Clothing Men's...,Trang phục nam,269.999 ₫,51% Off,1.9K Đã bán,4.8,753.0,Thành phố Hồ Chí Minh,https://www.lazada.vn/products/pdp-i2562394269...,https://img.lazcdn.com/g/p/6199d4f39b850a5a986...,JEEP SPIRIT Οfficial,https://www.lazada.vn/shop/jeep-spirit-fficial...
1,1329853406,"Bộ Đồ Thể Thao Xtep, Bộ Đồ Chạy Bộ Hai Mảnh Nh...",Trang phục nam,495.280 ₫,47% Off,550 Đã bán,4.9,207.0,China,https://www.lazada.vn/products/pdp-i1329853406...,https://img.lazcdn.com/g/p/a3467728107f63b3090...,XTEP Official Store,https://www.lazada.vn/shop/xtep-official-store...
2,3064932258,MOLAN Áo phông nam nam ngắn tay thể thao cổ tr...,Trang phục nam,38.000 ₫,50% Off,331 Đã bán,4.7,80.0,China,https://www.lazada.vn/products/pdp-i3064932258...,https://img.lazcdn.com/g/p/becc8492da7c50d2daa...,MOLAN Shopping Mall,https://www.lazada.vn/shop/molan-shopping-mall...
3,2250151368,"Trang Phục Tay Ngắn Thời Đường, Bộ Đồ Nam Chất...",Trang phục nam,212.430 ₫,33% Off,822 Đã bán,4.9,268.0,Ninh Bình,https://www.lazada.vn/products/pdp-i2250151368...,https://img.lazcdn.com/g/p/a71cbab85bdc3c27dc1...,Kem Thời Trang,https://www.lazada.vn/shop/kem-thoi-trang/?ite...
4,2964031932,Bộ Đồ Lụa Băng Tay Dài Cho Nam Mùa Xuân Hè Tập...,Trang phục nam,190.800 ₫,10% Off,288 Đã bán,4.6,28.0,China,https://www.lazada.vn/products/pdp-i2964031932...,https://img.lazcdn.com/g/ff/kf/Sd156b66e555c42...,NaN,https://www.lazada.vn/shop/lazada-global/?item...

In [2]:
import pandas as pd

df = pd.read_csv("data/lazada_trang_phuc_nam.csv")
display(df.head())

,ID Sản phẩm,Tên sản phẩm,Danh mục,Giá,Giảm giá,Đã bán,Điểm đánh giá,Lượt đánh giá,Địa điểm,Đường dẫn,Hình ảnh,Tên shop,Shop URL
0,2562394269,Jeep Spirit Outdoor Windbreaker Clothing Men's...,Trang phục nam,269.999 ₫,51% Off,1.9K Đã bán,4.8,753.0,Thành phố Hồ Chí Minh,https://www.lazada.vn/products/pdp-i2562394269...,https://img.lazcdn.com/g/p/6199d4f39b850a5a986...,JEEP SPIRIT Οfficial,https://www.lazada.vn/shop/jeep-spirit-fficial...
1,1329853406,"Bộ Đồ Thể Thao Xtep, Bộ Đồ Chạy Bộ Hai Mảnh Nh...",Trang phục nam,495.280 ₫,47% Off,550 Đã bán,4.9,207.0,China,https://www.lazada.vn/products/pdp-i1329853406...,https://img.lazcdn.com/g/p/a3467728107f63b3090...,XTEP Official Store,https://www.lazada.vn/shop/xtep-official-store...
2,3064932258,MOLAN Áo phông nam nam ngắn tay thể thao cổ tr...,Trang phục nam,38.000 ₫,50% Off,331 Đã bán,4.7,80.0,China,https://www.lazada.vn/products/pdp-i3064932258...,https://img.lazcdn.com/g/p/becc8492da7c50d2daa...,MOLAN Shopping Mall,https://www.lazada.vn/shop/molan-shopping-mall...
3,2250151368,"Trang Phục Tay Ngắn Thời Đường, Bộ Đồ Nam Chất...",Trang phục nam,212.430 ₫,33% Off,822 Đã bán,4.9,268.0,Ninh Bình,https://www.lazada.vn/products/pdp-i2250151368...,https://img.lazcdn.com/g/p/a71cbab85bdc3c27dc1...,Kem Thời Trang,https://www.lazada.vn/shop/kem-thoi-trang/?ite...
4,2964031932,Bộ Đồ Lụa Băng Tay Dài Cho Nam Mùa Xuân Hè Tập...,Trang phục nam,190.800 ₫,10% Off,288 Đã bán,4.6,28.0,China,https://www.lazada.vn/products/pdp-i2964031932...,https://img.lazcdn.com/g/ff/kf/Sd156b66e555c42...,NaN,https://www.lazada.vn/shop/lazada-global/?item...

In [ ]:
import time
import re
from bs4 import BeautifulSoup
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from concurrent.futures import ThreadPoolExecutor
import threading
import queue
import pandas as pd
import random
import winsound
import os

MAX_WORKERS = 6  # Số luồng (cửa sổ Chrome) chạy song song

# ===================== KHỞI TẠO CƠ CHẾ ĐA LUỒNG =====================
# 1. Hàng đợi để phân phát ID Profile cho các luồng (0, 1, 2)
profile_queue = queue.Queue()
for i in range(MAX_WORKERS):
    profile_queue.put(i)

# 2. Khóa (Lock) để tránh các luồng đụng độ nhau lúc khởi tạo driver
chrome_init_lock = threading.Lock()

def crawl_and_parse_shop_profile(url):
    # Lấy 1 ID từ hàng đợi rảnh rỗi
    profile_id = profile_queue.get()
    
    # Template chứa dữ liệu mặc định (để nếu lỗi vẫn không bị thiếu cột)
    extracted_data = {
        'Shop URL': url,
        'Seller ID': None,
        'Loại cửa hàng': None,
        'Followers': None,
        'Đánh giá người bán': None,
        'Danh mục chính': None,
        'Đã tham gia': None,
        'Giao đúng hẹn': None,
        'Tỷ lệ hủy đơn': None,
        'Tỷ lệ phản hồi chat': None
    }
    
    driver = None
    html = "" # Biến chứa HTML lấy được
    
    try:
        print(f"[Luồng {profile_id}] Đang khởi tạo trình duyệt Chrome...")
        options = uc.ChromeOptions()
        options.add_argument('--disable-gpu')
        options.add_argument('--window-size=1920,1080')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        
        # 🟢 CHIẾN THUẬT QUAN TRỌNG CHỐNG "BÓP" HIỆU NĂNG KHI CHẠY ĐA LUỒNG
        # Ép Chrome vẫn phải tải Javascript ở mức tối đa dù cửa sổ bị ẩn/che khuất
        options.add_argument("--disable-background-timer-throttling")
        options.add_argument("--disable-backgrounding-occluded-windows")
        options.add_argument("--disable-renderer-backgrounding")
        
        # Mỗi luồng sử dụng một thư mục user-data riêng biệt
        profile_path = rf'C:\Users\ADMIN\ChromeProfileData_{profile_id}'
        options.add_argument(f'--user-data-dir={profile_path}')
        
        # Có Lock để tránh bị lỗi WinError 183
        with chrome_init_lock:
            driver = uc.Chrome(options=options)
            
        print(f"[Luồng {profile_id}] Đang truy cập URL Hồ Sơ Cửa Hàng: \n{url}")
        driver.get(url)
        
        # ==========================================================
        # --- CƠ CHẾ KIỂM TRA & VƯỢT BOT DETECTION ---
        time.sleep(3)
        page_source_lower = driver.page_source.lower()
        if "we need to check if you are a robot" in page_source_lower or "recaptcha" in page_source_lower or "bảo vệ bởi ddos" in page_source_lower:
            print(f"[Luồng {profile_id}] PHÁT HIỆN BOT! Vui lòng tự giải Captcha trên cửa sổ {profile_id}...")
            
            try:
                for _ in range(5):
                    winsound.Beep(1500, 500)
                    time.sleep(0.1)
            except:
                pass

            try:
                WebDriverWait(driver, 60).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'seller-name__detail')) 
                )
                print(f"[Luồng {profile_id}] Đã qua bước xác minh.")
            except Exception:
                print(f"[Luồng {profile_id}] Quá 60s không giải được vòng lặp.")
        # ==========================================================
        
        print(f"[Luồng {profile_id}] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...")
        
        # Đợi cơ bản 10 giây để nạp khung hình
        time.sleep(10) 
        driver.execute_script("window.scrollBy(0, 500);")
        time.sleep(5)
        
        # 🟢 KIỂM TRA LINH HOẠT XEM THÔNG TIN ĐÃ LOAD LÊN DOM CHƯA
        # Cho phép kịch bản tối đa 3 lần đợi thêm. Nếu CPU lag khiến mạng rớt nhịp, máy sẽ thông minh xin chờ thêm 5 giây.
        for _ in range(3):
            temp_source = driver.page_source
            # Kiểm tra xem có 1 trong các chữ số thống kê được render thành công chưa
            if ("Giao đúng hẹn" in temp_source) or ("Shipped on time" in temp_source) or ("Đánh giá người bán" in temp_source) or ("Đã tham gia" in temp_source):
                break
            else:
                print(f"[Luồng {profile_id}] ⏳ Web bị lag chưa kịp đổ dữ liệu xuống, đang cố đợi thêm 5s...")
                time.sleep(5)
                driver.execute_script("window.scrollBy(0, 300);")
        
        # Chỉ lưu biến HTML trực tiếp lên RAM
        html = driver.page_source
        
    except Exception as e:
        print(f"[Luồng {profile_id}] Lỗi trong quá trình thao tác với Chrome: {e}")
    finally:
        # Luôn phải tắt driver để giải phóng RAM + trả profile lại hàng đợi
        try:
            if driver:
                driver.quit()
        except:
            pass
        profile_queue.put(profile_id)
        
    # --- PHÂN TÍCH DATA NGAY TỨC THÌ NẾU LẤY ĐƯỢC HTML ---
    if html:
        print(f"[Luồng {profile_id}] Đang bóc tách dữ liệu từ HTML...")
        soup = BeautifulSoup(html, 'html.parser')
        all_text = ' '.join(soup.stripped_strings)

        is_mall = bool(soup.find('img', alt='storeIcon'))
        extracted_data['Loại cửa hàng'] = 'LazMall' if is_mall else 'Shop Thường'

        seller_id_match = re.search(r'"sellerId"\s*:\s*(\d+)', html)
        if seller_id_match:
            extracted_data['Seller ID'] = seller_id_match.group(1)
        else: 
            shop_id_match = re.search(r'"shopId"\s*:\s*(\d+)', html)
            if shop_id_match:
                extracted_data['Seller ID'] = shop_id_match.group(1)

        followers = re.search(r'([0-9,]+)\s+Followers', all_text)
        if followers: extracted_data['Followers'] = followers.group(1)

        positive_rating = re.search(r'([0-9,.]+%)\s+(?:Đánh giá người bán|Seller Ratings)', all_text)
        if positive_rating: extracted_data['Đánh giá người bán'] = positive_rating.group(1)

        category_match = re.search(r'(?:Danh mục chính|Main category)(.*?)(?:Đã tham gia|Joined)', all_text)
        if category_match: 
            clean_category = re.sub(r'[^\w\s\'\-\&]', '', category_match.group(1)).strip()
            extracted_data['Danh mục chính'] = clean_category

        joined = re.search(r'(?:Đã tham gia|Joined)(?:.*?)\s+(\d+\s*\+?\s*(?:năm|years?|tháng|months?))', all_text)
        if joined: extracted_data['Đã tham gia'] = joined.group(1).strip()

        ship_on_time = re.search(r'(?:Giao đúng hẹn|Shipped on time)(?:.*?)\s+([0-9,.]+%|Không đủ dữ liệu|Not enough data)', all_text)
        if ship_on_time: extracted_data['Giao đúng hẹn'] = ship_on_time.group(1).strip()

        cancel_rate = re.search(r'(?:Tỷ lệ hủy đơn|Cancellation rate)(?:.*?)\s+([0-9,.]+%|Không đủ dữ liệu|Not enough data)', all_text)
        if cancel_rate: extracted_data['Tỷ lệ hủy đơn'] = cancel_rate.group(1).strip()

        chat_response = re.search(r'(?:tin nhắn trong 10|10 Minutes Response Rate)(?:.*?)\s+([0-9,.]+%)', all_text)
        if chat_response: extracted_data['Tỷ lệ phản hồi chat'] = chat_response.group(1).strip()
        
        print(f"[Luồng {profile_id}] ✅ Đã trích xuất xong dữ liệu cho một shop.")
        
    return extracted_data

raw_urls = df['Shop URL'].dropna().unique()

danh_sach_shop_urls = []
for url in raw_urls:
    # Link cũ thường có dạng: https://www.lazada.vn/shop/abc-store/?itemId=123...
    # split('?') sẽ cắt lấy phần gốc: https://www.lazada.vn/shop/abc-store/
    base_url = url.split('?')[0] 
    
    # Ghép thêm đuôi đi thẳng vào Tab Profile của shop đó
    profile_url = f"{base_url}?path=profile.htm&pageTypeId=3"
    
    # Tránh trường hợp 1 shop có nhiều link kiểu base_url giống nhau nhưng parameter # nhau mọc ra
    if profile_url not in danh_sach_shop_urls:
        danh_sach_shop_urls.append(profile_url)

print(f"Tổng số Shop cần cào thông tin hồ sơ (đã lọc trùng): {len(danh_sach_shop_urls)}")


# ===================== THỰC THI CHẠY ĐA LUỒNG =====================

def wrapper_process(url):
    time.sleep(random.uniform(1, 4)) # Delay nhẹ cho đỡ gửi dồn dập
    return crawl_and_parse_shop_profile(url)

print(f"→ Sẽ crawl {len(danh_sach_shop_urls)} Shop URL với {MAX_WORKERS} luồng song song...\n")

all_results = []
with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = executor.map(wrapper_process, danh_sach_shop_urls)
    
    for result in futures:
        if result:
            all_results.append(result)

# ===== TỔNG HỢP VÀ GHI RA FILE CSV =====
df_profile = pd.DataFrame(all_results)
# Đổi tên biến sang csv_file và để đuôi .csv
csv_file = os.path.join("data", "lazada_shop_profiles_final_tpnam.csv")
# Sử dụng hàm df_profile.to_csv thay vì to_excel
# Thêm utf-8-sig để đọc tiếng Việt chuẩn xác trong Excel
df_profile.to_csv(csv_file, index=False, encoding="utf-8-sig")
print(f"Đã lưu thành công file CSV tại: {csv_file}!")

print(f"\n====== HOÀN TẤT ======")
print(f"✅ Đã xử lý tổng cộng {len(all_results)} shop.")

# Hiển thị xem trước
display(df_profile.head())

Tổng số Shop cần cào thông tin hồ sơ (đã lọc trùng): 460
→ Sẽ crawl 460 Shop URL với 6 luồng song song...

[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 5] Đang khởi tạo trình duyệt Chrome...
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/kanaya/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/xtep-official-store/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/kem-thoi-trang/?path=profile.htm&pageTypeId=3
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/molan-shopping-mall/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/lazada-global/?path=profile.htm&pageTypeId=3
[Luồng 5] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/jeep-spirit-fficial/?path=profile.htm&pageTypeId=3
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 5] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 5] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 5] Đang khởi tạo trình duyệt Chrome...
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/hoang-kim-anh/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/thoi-trang-cua-bo/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/giabao-shop-1596350182/?path=profile.htm&pageTypeId=3
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/trang-phuc-dao-cu-bieu-dien-dung-trum/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/xuong-si-quan-ao-1587100905/?path=profile.htm&pageTypeId=3
[Luồng 5] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/dsgsdgfhfdh/?path=profile.htm&pageTypeId=3
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/luna-lh/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 5] Đang bóc tách dữ liệu từ HTML...
[Luồng 5] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/cappa-sop/?path=profile.htm&pageTypeId=3
[Luồng 5] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/giaysyquancom/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/mpathw-mall/?path=profile.htm&pageTypeId=3
[Luồng 5] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/do-lam-hong-phuc-an/?path=profile.htm&pageTypeId=3
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/kq-shop/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/diorgino/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 5] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 5] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/phap-phuc-hoang-nghia/?path=profile.htm&pageTypeId=3
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/star-fruit-mall/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 5] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/ajfqs6jn/?path=profile.htm&pageTypeId=3
[Luồng 5] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/kho-giay-si-quan/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/lamando/?path=profile.htm&pageTypeId=3
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/tb-supermarket-store/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 5] Đang bóc tách dữ liệu từ HTML...
[Luồng 5] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/bulbal-viet-nam/?path=profile.htm&pageTypeId=3
[Luồng 5] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/tokyoshop/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/sea-jjt-mall/?path=profile.htm&pageTypeId=3
[Luồng 5] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/zuki-shop-th/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/hungphuocfashion/?path=profile.htm&pageTypeId=3
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] PHÁT HIỆN BOT! Vui lòng tự giải Captcha trên cửa sổ 5...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/nguyendongphuc/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/ryeytruj/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/live-great/?path=profile.htm&pageTypeId=3
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/win-69/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/gen-alpha/?path=profile.htm&pageTypeId=3
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/quangthoitrang/?path=profile.htm&pageTypeId=3
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/hong-phuc-an/?path=profile.htm&pageTypeId=3
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/do-lam-ao-lam/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/the-deme-store/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/shop-sale-off/?path=profile.htm&pageTypeId=3
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 5] Quá 60s không giải được vòng lặp.
[Luồng 5] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/kaystore-online/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/xuzi-fashion/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.[Luồng 3] Đang khởi tạo trình duyệt Chrome...

[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/hparx84x/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/quan-jean-nam-vuong-nam/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/ponivalaza/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang bóc tách dữ liệu từ HTML...
[Luồng 5] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang khởi tạo trình duyệt Chrome...
[Luồng 5] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/hanlu-style/?path=profile.htm&pageTypeId=3
[Luồng 5] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/shop-vonesa/?path=profile.htm&pageTypeId=3
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/dubaishop/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/ndxnedsl/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/phap-phuc-thu-keo/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/thoi-trang-bull-kid/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang bóc tách dữ liệu từ HTML...
[Luồng 5] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang khởi tạo trình duyệt Chrome...
[Luồng 5] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/avan-fashion/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/gym-pt68-stores/?path=profile.htm&pageTypeId=3
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/gia-loc-officall/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/platinum-menswear/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/laddy-mall/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/xuongnitnt/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang bóc tách dữ liệu từ HTML...
[Luồng 5] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 5] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/trathiennhienminhtam/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 2] Đang bóc tách dữ liệu từ HTML...
[Luồng 2] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang bóc tách dữ liệu từ HTML...
[Luồng 0] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 2] Đang khởi tạo trình duyệt Chrome...
[Luồng 2] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/tao-anime/?path=profile.htm&pageTypeId=3
[Luồng 0] Đang khởi tạo trình duyệt Chrome...
[Luồng 3] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 0] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/t-t08-store/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang bóc tách dữ liệu từ HTML...
[Luồng 3] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 4] Đang bóc tách dữ liệu từ HTML...
[Luồng 4] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/shop-x-men/?path=profile.htm&pageTypeId=3
[Luồng 1] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang khởi tạo trình duyệt Chrome...
[Luồng 1] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/tamlinhngocbao/?path=profile.htm&pageTypeId=3
[Luồng 4] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/tb-fashion-store/?path=profile.htm&pageTypeId=3
[Luồng 2] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 0] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang bóc tách dữ liệu từ HTML...
[Luồng 5] ✅ Đã trích xuất xong dữ liệu cho một shop.
[Luồng 3] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 1] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang khởi tạo trình duyệt Chrome...
[Luồng 4] Đang đợi toàn bộ chỉ số uy tín tải về màn hình...
[Luồng 5] Đang truy cập URL Hồ Sơ Cửa Hàng:
https://www.lazada.vn/shop/hoaithuong08082003/?path=profile.htm&pageTypeId=3

NameError: name 'excel_file' is not defined

In [4]:
# ===== TỔNG HỢP VÀ GHI RA FILE CSV =====
df_profile = pd.DataFrame(all_results)
# Đổi tên biến sang csv_file và để đuôi .csv
csv_file = os.path.join("data", "lazada_shop_profiles_final_tpnam.csv")
# Sử dụng hàm df_profile.to_csv thay vì to_excel
# Thêm utf-8-sig để đọc tiếng Việt chuẩn xác trong Excel
df_profile.to_csv(csv_file, index=False, encoding="utf-8-sig")
print(f"Đã lưu thành công file CSV tại: {csv_file}!")

print(f"\n====== HOÀN TẤT ======")
print(f"✅ Đã xử lý tổng cộng {len(all_results)} shop.")

# Hiển thị xem trước
display(df_profile.head())

Đã lưu thành công file CSV tại: data\lazada_shop_profiles_final_tpnam.csv!

====== HOÀN TẤT ======
✅ Đã xử lý tổng cộng 460 shop.

,Shop URL,Seller ID,Loại cửa hàng,Followers,Đánh giá người bán,Danh mục chính,Đã tham gia,Giao đúng hẹn,Tỷ lệ hủy đơn,Tỷ lệ phản hồi chat
0,https://www.lazada.vn/shop/jeep-spirit-fficial...,200227335601,LazMall,5896,94%,Men's Clothing,3 + năm,94%,None,83.33%
1,https://www.lazada.vn/shop/xtep-official-store...,100024592,LazMall,68203,98%,Sports Shoes and Clothing,8 + năm,98%,None,93.75%
2,https://www.lazada.vn/shop/molan-shopping-mall...,200163300057,LazMall,11391,100%,Men's Clothing,5 + năm,None,None,90.80%
3,https://www.lazada.vn/shop/kem-thoi-trang/?pat...,200168727341,Shop Thường,4720,96%,Men's Clothing,4 + năm,100%,None,100.00%
4,https://www.lazada.vn/shop/lazada-global/?path...,100174125,Shop Thường,1282011,95%,Tools & Home Improvement,7 + năm,83%,4%,95.47%